(() => {

    const mainCardsData = [{
            "imageName": "angry",
            "cardTitle": "emotions"
        }, {
            "imageName": "bird",
            "cardTitle": "animals (set A)"
        }, {
            "imageName": "cat",
            "cardTitle": "animals (set B)"
        }, {
            "imageName": "blouse",
            "cardTitle": "clothes"
        }, {
            "imageName": "swim",
            "cardTitle": "action(set A)"
        }, {
            "imageName": "point",
            "cardTitle": "action(set B)"
        },
        {
            "imageName": "eggplant",
            "cardTitle": "vegetables"
        }
    ]

    let playCardsData = {
        "emotions": [{
            "imageName": "angry",
            "ruCaption": "злой",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "scared",
            "ruCaption": "испуганный",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "tired",
            "ruCaption": "Уставший",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "surprised",
            "ruCaption": "удивленный",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "smile",
            "ruCaption": "улыбка",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "laugh",
            "ruCaption": "смех",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "sad",
            "ruCaption": "грустный",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "happy",
            "ruCaption": "счастливый",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }],
        "animals (set A)": [{
            "imageName": "bird",
            "ruCaption": "птица",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "rabbit",
            "ruCaption": "кролик",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "pig",
            "ruCaption": "свинья",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "lion",
            "ruCaption": "лев",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "mouse",
            "ruCaption": "мышь",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "horse",
            "ruCaption": "лошадь",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "dolphin",
            "ruCaption": "дельфин",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "fish",
            "ruCaption": "рыба",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }],
        "animals (set B)": [{
            "imageName": "cat",
            "ruCaption": "кот",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "giraffe",
            "ruCaption": "жираф",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "sheep",
            "ruCaption": "овца",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "dog",
            "ruCaption": "собака",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "chicken",
            "ruCaption": "курица",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "chick",
            "ruCaption": "цыплёнок",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "turtle",
            "ruCaption": "черепаха",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "frog",
            "ruCaption": "лягушка",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }],
        "clothes": [{
            "imageName": "blouse",
            "ruCaption": "блузка",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "dress",
            "ruCaption": "платье",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "coat",
            "ruCaption": "пальто",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "pants",
            "ruCaption": "штаны",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "shirt",
            "ruCaption": "рубашка",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "skirt",
            "ruCaption": "юбка",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "boot",
            "ruCaption": "ботинки",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "shoe",
            "ruCaption": "туфли",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }],
        "action(set A)": [{
            "imageName": "swim",
            "ruCaption": "плавать",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "skip",
            "ruCaption": "пропускать",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "sing",
            "ruCaption": "петь",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "play",
            "ruCaption": "играть",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "cry",
            "ruCaption": "плакать",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "run",
            "ruCaption": "бегать",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "open",
            "ruCaption": "открывать",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "ride",
            "ruCaption": "ехать",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }],
        "action(set B)": [{
            "imageName": "point",
            "ruCaption": "указывать",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "draw",
            "ruCaption": "рисовать",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "dance",
            "ruCaption": "танцевать",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "fish",
            "ruCaption": "ловить рыбу",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "hug",
            "ruCaption": "обнимать",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "jump",
            "ruCaption": "прыгать",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "fly",
            "ruCaption": "летать",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "dive",
            "ruCaption": "нырять",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }],
        "vegetables": [{
            "imageName": "eggplant",
            "ruCaption": "баклажан",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "carrot",
            "ruCaption": "морковка",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "cucumber",
            "ruCaption": "огурец",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "pumpkin",
            "ruCaption": "тыква",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "beet",
            "ruCaption": "свекла",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "tomato",
            "ruCaption": "помидор",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "sad",
            "ruCaption": "грустный",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }, {
            "imageName": "happy",
            "ruCaption": "счастливый",
            "trainCounter": 0,
            "correctCounter": 0,
            "wrongCounter": 0 
        }],
        "cardId": [{
            "imageName": "angry",
            "ruCaption": "злой"
        }, {
            "imageName": "scared",
            "ruCaption": "испуганный"
        }, {
            "imageName": "tired",
            "ruCaption": "Уставший"
        }, {
            "imageName": "surprised",
            "ruCaption": "удивленный"
        }, {
            "imageName": "smile",
            "ruCaption": "улыбка"
        }, {
            "imageName": "laugh",
            "ruCaption": "смех"
        }, {
            "imageName": "sad",
            "ruCaption": "грустный"
        }, {
            "imageName": "happy",
            "ruCaption": "счастливый"
        }],
    }

    if (localStorage.getItem('data') === null) {
        console.log('ddd');
        localStorage.setItem('data', JSON.stringify(playCardsData));
    }

    window.data = {
        mainCardsData: mainCardsData,
        playCardsData: playCardsData
    }
})()